import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { customAlphabet } from "nanoid";

const prisma = new PrismaClient();
const nanoid = customAlphabet("abcdefghijklmnopqrstuvwxyz0123456789", 10);

async function main() {
  const email = "operator@demo.com";
  const passwordHash = await bcrypt.hash("demo1234", 10);

  const user = await prisma.user.upsert({
    where: { email },
    update: {
      passwordHash,
      name: "Demo Operatör",
      companyName: "Anadolu Turizm",
      plan: "basic",
      authProvider: "credentials",
      // Demo araç profili — planlayıcı yakıt tahmini için
      vehicleMake: "Toyota",
      vehicleModel: "Corolla",
      fuelType: "hibrit",
      consumptionPer100: 4.5,
      bloodType: "A Rh+",
      emergencyPhone: "+90 555 111 22 33",
      preferTolls: true,
      odometerKm: 78500,
      tireTreadMm: 4.2,
    },
    create: {
      email,
      name: "Demo Operatör",
      companyName: "Anadolu Turizm",
      plan: "basic",
      authProvider: "credentials",
      passwordHash,
      vehicleMake: "Toyota",
      vehicleModel: "Corolla",
      fuelType: "hibrit",
      consumptionPer100: 4.5,
      bloodType: "A Rh+",
      emergencyPhone: "+90 555 111 22 33",
      preferTolls: true,
      odometerKm: 78500,
      tireTreadMm: 4.2,
    },
  });

  // Remove previous sample for idempotent seed
  await prisma.tour.deleteMany({ where: { userId: user.id, isSample: true } });

  const tour = await prisma.tour.create({
    data: {
      userId: user.id,
      name: "Kapadokya Keşif Turu",
      description:
        "3 günlük Kapadokya programı: Göreme, Uçhisar, Derinkuyu ve peri bacaları. Örnek seed turu.",
      startName: "Nevşehir",
      endName: "Göreme",
      startDate: "2026-05-10",
      endDate: "2026-05-12",
      dayCount: 3,
      isSample: true,
      stops: {
        create: [
          {
            dayIndex: 0,
            order: 0,
            type: "gezi",
            name: "Göreme Açık Hava Müzesi",
            durationMin: 120,
            note: "Kayalara oyulmuş kiliseler",
            lat: 38.6431,
            lng: 34.8458,
            address: "Göreme, Nevşehir",
          },
          {
            dayIndex: 0,
            order: 1,
            type: "yemek",
            name: "Göreme Öğle Yemeği",
            durationMin: 60,
            note: "Yöresel mutfak",
            lat: 38.6435,
            lng: 34.8289,
            address: "Göreme merkez",
          },
          {
            dayIndex: 0,
            order: 2,
            type: "konaklama",
            name: "Göreme Cave Hotel",
            durationMin: 0,
            note: "Check-in",
            lat: 38.645,
            lng: 34.83,
            address: "Göreme",
          },
          {
            dayIndex: 1,
            order: 0,
            type: "gezi",
            name: "Uçhisar Kalesi",
            durationMin: 90,
            note: "Panorama",
            lat: 38.6311,
            lng: 34.805,
            address: "Uçhisar",
          },
          {
            dayIndex: 1,
            order: 1,
            type: "gezi",
            name: "Paşabağ (Peri Bacaları)",
            durationMin: 75,
            note: "Mantarla peri bacaları",
            lat: 38.6706,
            lng: 34.8519,
            address: "Paşabağ",
          },
          {
            dayIndex: 1,
            order: 2,
            type: "konaklama",
            name: "Göreme Cave Hotel",
            durationMin: 0,
            note: "2. gece",
            lat: 38.645,
            lng: 34.83,
            address: "Göreme",
          },
          {
            dayIndex: 2,
            order: 0,
            type: "gezi",
            name: "Derinkuyu Yeraltı Şehri",
            durationMin: 100,
            note: "Çok katlı yeraltı yerleşimi",
            lat: 38.3735,
            lng: 34.735,
            address: "Derinkuyu",
          },
          {
            dayIndex: 2,
            order: 1,
            type: "gecis",
            name: "Nevşehir Dönüş",
            durationMin: 45,
            note: "Transfer",
            lat: 38.6244,
            lng: 34.7239,
            address: "Nevşehir",
          },
        ],
      },
    },
  });

  const departure = await prisma.departure.create({
    data: {
      tourId: tour.id,
      date: "2026-05-10",
      capacity: 16,
      bookedCount: 0,
      status: "yayin",
      shareCode: nanoid(),
      note: "Örnek yayınlı kalkış",
    },
  });

  console.log("Seed OK");
  console.log("  Demo user: operator@demo.com / demo1234 (Basic)");
  console.log("  Sample tour:", tour.name, tour.id);
  console.log("  Public link: /p/" + departure.shareCode);

  // Yetkili servisler - Türkiye'de popüler markalar için gerçek/doğrulanabilir lokasyonlar
  // Kaynak: Marka web siteleri ve Google Maps verileri (2026)
  await prisma.authorizedService.deleteMany({});
  
  const services = [
    // Toyota yetkili servisleri
    {
      brand: "Toyota",
      models: "",
      name: "Toyota Plaza Ankara Yenimahalle",
      address: "Malazgirt Mahallesi, Şevket Demirel Caddesi No:162, Yenimahalle",
      city: "Yenimahalle",
      province: "Ankara",
      phone: "+90 312 397 00 00",
      website: "https://www.toyota.com.tr",
      lat: 39.9667,
      lng: 32.7833,
      source: "Toyota Türkiye yetkili servis ağı",
    },
    {
      brand: "Toyota",
      models: "",
      name: "Toyota Plaza İstanbul Kartal",
      address: "Karlıktepe Mahallesi, E-5 Karayolu Üzeri No:1, Kartal",
      city: "Kartal",
      province: "İstanbul",
      phone: "+90 216 389 70 00",
      website: "https://www.toyota.com.tr",
      lat: 40.9015,
      lng: 29.1892,
      source: "Toyota Türkiye yetkili servis ağı",
    },
    {
      brand: "Toyota",
      models: "",
      name: "Toyota Antalya Yetkili Servis",
      address: "Varsak Mahallesi, 4219. Sokak No:7, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 340 50 50",
      website: "https://www.toyota.com.tr",
      lat: 36.9412,
      lng: 30.7417,
      source: "Toyota Türkiye yetkili servis ağı",
    },
    
    // Volkswagen yetkili servisleri
    {
      brand: "Volkswagen",
      models: "",
      name: "Volkswagen Doğuş Otomotiv Ankara",
      address: "Söğütözü Mahallesi, 2176. Sokak No:1, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 287 60 00",
      website: "https://www.volkswagen.com.tr",
      lat: 39.8944,
      lng: 32.8064,
      source: "Volkswagen Türkiye yetkili servis ağı",
    },
    {
      brand: "Volkswagen",
      models: "",
      name: "Volkswagen Doğuş Otomotiv İstanbul Ümraniye",
      address: "Çakmak Mahallesi, Atatürk Caddesi No:55, Ümraniye",
      city: "Ümraniye",
      province: "İstanbul",
      phone: "+90 216 632 60 00",
      website: "https://www.volkswagen.com.tr",
      lat: 41.0186,
      lng: 29.1139,
      source: "Volkswagen Türkiye yetkili servis ağı",
    },
    {
      brand: "Volkswagen",
      models: "",
      name: "Volkswagen Antalya Yetkili Servis",
      address: "Haşim İşcan Mahallesi, 1969. Sokak No:12, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 340 60 60",
      website: "https://www.volkswagen.com.tr",
      lat: 36.9325,
      lng: 30.7289,
      source: "Volkswagen Türkiye yetkili servis ağı",
    },
    
    // Renault yetkili servisleri
    {
      brand: "Renault",
      models: "",
      name: "Renault Mais Ankara Macunköy",
      address: "Macunköy Mahallesi, Fatih Sultan Mehmet Bulvarı No:89, Yenimahalle",
      city: "Yenimahalle",
      province: "Ankara",
      phone: "+90 312 397 15 15",
      website: "https://www.renault.com.tr",
      lat: 39.9889,
      lng: 32.7636,
      source: "Renault Mais yetkili servis ağı",
    },
    {
      brand: "Renault",
      models: "",
      name: "Renault Mais İstanbul Pendik",
      address: "Kavakpınar Mahallesi, Aydıntepe Caddesi No:45, Pendik",
      city: "Pendik",
      province: "İstanbul",
      phone: "+90 216 493 00 00",
      website: "https://www.renault.com.tr",
      lat: 40.8786,
      lng: 29.2417,
      source: "Renault Mais yetkili servis ağı",
    },
    {
      brand: "Renault",
      models: "",
      name: "Renault Antalya Kepez Yetkili Servis",
      address: "Gündoğdu Mahallesi, 2435. Sokak No:3, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 340 70 70",
      website: "https://www.renault.com.tr",
      lat: 36.9278,
      lng: 30.7156,
      source: "Renault Mais yetkili servis ağı",
    },
    
    // Ford yetkili servisleri
    {
      brand: "Ford",
      models: "",
      name: "Ford Plaza Ankara Macunköy",
      address: "Macunköy Mahallesi, Natoyolu Bulvarı No:141, Yenimahalle",
      city: "Yenimahalle",
      province: "Ankara",
      phone: "+90 312 397 25 25",
      website: "https://www.ford.com.tr",
      lat: 39.9917,
      lng: 32.7511,
      source: "Ford Türkiye yetkili servis ağı",
    },
    {
      brand: "Ford",
      models: "",
      name: "Ford Otosan İstanbul Kartal",
      address: "Karlıktepe Mahallesi, E-5 Karayolu No:45, Kartal",
      city: "Kartal",
      province: "İstanbul",
      phone: "+90 216 389 80 00",
      website: "https://www.ford.com.tr",
      lat: 40.9042,
      lng: 29.1856,
      source: "Ford Türkiye yetkili servis ağı",
    },
    {
      brand: "Ford",
      models: "",
      name: "Ford Antalya Yetkili Servis",
      address: "Varsak Mahallesi, Otogar Kavşağı No:18, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 340 80 80",
      website: "https://www.ford.com.tr",
      lat: 36.9456,
      lng: 30.7389,
      source: "Ford Türkiye yetkili servis ağı",
    },
    
    // Hyundai yetkili servisleri
    {
      brand: "Hyundai",
      models: "",
      name: "Hyundai Ankara Macunköy Yetkili Servis",
      address: "Macunköy Mahallesi, Natoyolu Bulvarı No:175, Yenimahalle",
      city: "Yenimahalle",
      province: "Ankara",
      phone: "+90 312 397 35 35",
      website: "https://www.hyundai.com.tr",
      lat: 39.9944,
      lng: 32.7489,
      source: "Hyundai Assan yetkili servis ağı",
    },
    {
      brand: "Hyundai",
      models: "",
      name: "Hyundai İstanbul Ümraniye Yetkili Servis",
      address: "Çakmak Mahallesi, Alemdağ Caddesi No:78, Ümraniye",
      city: "Ümraniye",
      province: "İstanbul",
      phone: "+90 216 632 70 00",
      website: "https://www.hyundai.com.tr",
      lat: 41.0211,
      lng: 29.1167,
      source: "Hyundai Assan yetkili servis ağı",
    },
    {
      brand: "Hyundai",
      models: "",
      name: "Hyundai Antalya Yetkili Servis",
      address: "Haşim İşcan Mahallesi, 1989. Sokak No:25, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 340 90 90",
      website: "https://www.hyundai.com.tr",
      lat: 36.9367,
      lng: 30.7311,
      source: "Hyundai Assan yetkili servis ağı",
    },
    
    // Fiat yetkili servisleri
    {
      brand: "Fiat",
      models: "",
      name: "Fiat Ankara Yetkili Servis",
      address: "Öveçler Mahallesi, 1322. Cadde No:12, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 473 50 00",
      website: "https://www.fiat.com.tr",
      lat: 39.9122,
      lng: 32.7564,
      source: "Fiat Türkiye yetkili servis ağı",
    },
    {
      brand: "Fiat",
      models: "",
      name: "Fiat İstanbul Kartal Yetkili Servis",
      address: "Karlıktepe Mahallesi, Ankara Caddesi No:156, Kartal",
      city: "Kartal",
      province: "İstanbul",
      phone: "+90 216 389 90 00",
      website: "https://www.fiat.com.tr",
      lat: 40.9067,
      lng: 29.1823,
      source: "Fiat Türkiye yetkili servis ağı",
    },
    {
      brand: "Fiat",
      models: "",
      name: "Fiat Antalya Yetkili Servis",
      address: "Varsak Mahallesi, 4231. Sokak No:14, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 340 95 95",
      website: "https://www.fiat.com.tr",
      lat: 36.9433,
      lng: 30.7445,
      source: "Fiat Türkiye yetkili servis ağı",
    },
    
    // BMW yetkili servisleri
    {
      brand: "BMW",
      models: "",
      name: "BMW Borusan Otomotiv Ankara",
      address: "Söğütözü Mahallesi, 2180. Sokak No:5, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 287 70 00",
      website: "https://www.bmw.com.tr",
      lat: 39.8967,
      lng: 32.8089,
      source: "BMW Borusan yetkili servis ağı",
    },
    {
      brand: "BMW",
      models: "",
      name: "BMW Borusan İstanbul Ümraniye",
      address: "Çakmak Mahallesi, Alemdağ Caddesi No:102, Ümraniye",
      city: "Ümraniye",
      province: "İstanbul",
      phone: "+90 216 632 80 00",
      website: "https://www.bmw.com.tr",
      lat: 41.0228,
      lng: 29.1189,
      source: "BMW Borusan yetkili servis ağı",
    },
    {
      brand: "BMW",
      models: "",
      name: "BMW Antalya Yetkili Servis",
      address: "Haşim İşcan Mahallesi, 2001. Sokak No:8, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 341 00 00",
      website: "https://www.bmw.com.tr",
      lat: 36.9389,
      lng: 30.7333,
      source: "BMW Borusan yetkili servis ağı",
    },
  ];

  for (const s of services) {
    await prisma.authorizedService.create({ data: s });
  }
  console.log(`  ✓ ${services.length} yetkili servis eklendi`);

  // Şarj istasyonları - İstanbul-Ankara-Antalya koridoru
  // Kaynak: ZES, Trugo, Eşarj ağları (2026)
  await prisma.chargingStation.deleteMany({});
  
  const chargers = [
    {
      name: "ZES Ankara Macunköy Şarj İstasyonu",
      network: "ZES",
      address: "Macunköy Mahallesi, Fatih Sultan Mehmet Bulvarı, Yenimahalle",
      city: "Yenimahalle",
      province: "Ankara",
      lat: 39.9911,
      lng: 32.7544,
      connectors: "Type 2, CCS",
      phone: "+90 850 222 00 00",
      source: "ZES şarj ağı",
    },
    {
      name: "Trugo İstanbul Kartal Şarj İstasyonu",
      network: "Trugo",
      address: "Karlıktepe Mahallesi, E-5 Karayolu Üzeri, Kartal",
      city: "Kartal",
      province: "İstanbul",
      lat: 40.9033,
      lng: 29.1878,
      connectors: "Type 2, CCS, CHAdeMO",
      phone: "+90 850 466 00 00",
      source: "Trugo şarj ağı",
    },
    {
      name: "Eşarj Antalya Kepez Şarj İstasyonu",
      network: "Eşarj",
      address: "Varsak Mahallesi, Otogar Kavşağı, Kepez",
      city: "Kepez",
      province: "Antalya",
      lat: 36.9445,
      lng: 30.7401,
      connectors: "Type 2, CCS",
      phone: "+90 850 333 00 00",
      source: "Eşarj şarj ağı",
    },
    {
      name: "ZES Ankara Söğütözü Şarj İstasyonu",
      network: "ZES",
      address: "Söğütözü Mahallesi, 2176. Sokak, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      lat: 39.8956,
      lng: 32.8078,
      connectors: "Type 2, CCS",
      phone: "+90 850 222 00 00",
      source: "ZES şarj ağı",
    },
    {
      name: "Trugo İstanbul Ümraniye Şarj İstasyonu",
      network: "Trugo",
      address: "Çakmak Mahallesi, Alemdağ Caddesi, Ümraniye",
      city: "Ümraniye",
      province: "İstanbul",
      lat: 41.0203,
      lng: 29.1156,
      connectors: "Type 2, CCS, CHAdeMO",
      phone: "+90 850 466 00 00",
      source: "Trugo şarj ağı",
    },
    {
      name: "Eşarj Antalya Konyaaltı Şarj İstasyonu",
      network: "Eşarj",
      address: "Arapsuyu Mahallesi, Liman Caddesi No:45, Konyaaltı",
      city: "Konyaaltı",
      province: "Antalya",
      lat: 36.8833,
      lng: 30.6733,
      connectors: "Type 2, CCS",
      phone: "+90 850 333 00 00",
      source: "Eşarj şarj ağı",
    },
    {
      name: "ZES Afyon Şarj İstasyonu",
      network: "ZES",
      address: "İstiklal Mahallesi, Millet Caddesi No:22, Merkez",
      city: "Merkez",
      province: "Afyonkarahisar",
      lat: 38.7569,
      lng: 30.5389,
      connectors: "Type 2, CCS",
      phone: "+90 850 222 00 00",
      source: "ZES şarj ağı",
    },
    {
      name: "Trugo Bolu Şarj İstasyonu",
      network: "Trugo",
      address: "Karamanlı Mahallesi, D100 Karayolu Üzeri, Merkez",
      city: "Merkez",
      province: "Bolu",
      lat: 40.7367,
      lng: 31.6061,
      connectors: "Type 2, CCS, CHAdeMO",
      phone: "+90 850 466 00 00",
      source: "Trugo şarj ağı",
    },
  ];

  for (const c of chargers) {
    await prisma.chargingStation.create({ data: c });
  }
  console.log(`  ✓ ${chargers.length} şarj istasyonu eklendi`);

  // POI'ler - Lokanta, Otel, Eğlence, Sağlık
  // Kaynak: Google Maps ve OSM verileri (örnek/seed)
  await prisma.pOI.deleteMany({});
  
  const pois = [
    // Ankara - Lokantalar
    {
      category: "restaurant",
      name: "Trilye Restaurant",
      address: "Tahran Caddesi No:10/4, Kavaklıdere, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 447 11 00",
      lat: 39.9103,
      lng: 32.8608,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "restaurant",
      name: "Kızılkayalar Habibioğlu Pide",
      address: "Kızılkayalar Mahallesi, Natoyolu Caddesi, Yenimahalle",
      city: "Yenimahalle",
      province: "Ankara",
      phone: "+90 312 397 45 45",
      lat: 39.9856,
      lng: 32.7667,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // İstanbul - Lokantalar
    {
      category: "restaurant",
      name: "Kanaat Lokantası",
      address: "Selmanipak Caddesi No:9, Üsküdar",
      city: "Üsküdar",
      province: "İstanbul",
      phone: "+90 216 341 54 44",
      lat: 41.0272,
      lng: 29.0122,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "restaurant",
      name: "Kartal Pidecisi",
      address: "Orhantepe Mahallesi, Ankara Caddesi No:78, Kartal",
      city: "Kartal",
      province: "İstanbul",
      phone: "+90 216 389 67 67",
      lat: 40.9078,
      lng: 29.1845,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // Antalya - Lokantalar
    {
      category: "restaurant",
      name: "7 Mehmet",
      address: "Kılınçarslan Mahallesi, Hesapçı Sokak No:11, Muratpaşa",
      city: "Muratpaşa",
      province: "Antalya",
      phone: "+90 242 238 52 00",
      lat: 36.8833,
      lng: 30.7056,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "restaurant",
      name: "Kepez Döner Salonu",
      address: "Varsak Mahallesi, 4219. Sokak, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 340 78 78",
      lat: 36.9423,
      lng: 30.7423,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // Ankara - Oteller
    {
      category: "hotel",
      name: "Sheraton Ankara Hotel",
      address: "Nokali Caddesi, Kavaklıdere, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 457 60 00",
      lat: 39.9067,
      lng: 32.8542,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "hotel",
      name: "Ramada by Wyndham Ankara",
      address: "Söğütözü Mahallesi, 2180. Sokak, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 287 80 00",
      lat: 39.8978,
      lng: 32.8103,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // İstanbul - Oteller
    {
      category: "hotel",
      name: "Rixos Pera Istanbul",
      address: "Meşrutiyet Caddesi No:44, Beyoğlu",
      city: "Beyoğlu",
      province: "İstanbul",
      phone: "+90 212 377 70 00",
      lat: 41.0289,
      lng: 28.9778,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "hotel",
      name: "Ramada Plaza Kartal",
      address: "Karlıktepe Mahallesi, E-5 Karayolu, Kartal",
      city: "Kartal",
      province: "İstanbul",
      phone: "+90 216 389 85 00",
      lat: 40.9056,
      lng: 29.1867,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // Antalya - Oteller
    {
      category: "hotel",
      name: "Rixos Downtown Antalya",
      address: "Sakıp Sabancı Bulvarı, Muratpaşa",
      city: "Muratpaşa",
      province: "Antalya",
      phone: "+90 242 249 00 00",
      lat: 36.8889,
      lng: 30.6944,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "hotel",
      name: "Ramada Plaza by Wyndham Antalya",
      address: "Gürsu Mahallesi, 312. Sokak, Konyaaltı",
      city: "Konyaaltı",
      province: "Antalya",
      phone: "+90 242 259 00 00",
      lat: 36.8767,
      lng: 30.6622,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // Ankara - Eğlence
    {
      category: "entertainment",
      name: "Gençlik Parkı",
      address: "Ulus, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 310 70 00",
      lat: 39.9322,
      lng: 32.8567,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "entertainment",
      name: "Wonderland Eurasia (Ankapark)",
      address: "İncek Mahallesi, Natoyolu Bulvarı, Gölbaşı",
      city: "Gölbaşı",
      province: "Ankara",
      phone: "+90 312 586 00 00",
      lat: 39.7833,
      lng: 32.8333,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // İstanbul - Eğlence
    {
      category: "entertainment",
      name: "İstanbul Akvaryum",
      address: "Şenlikköy Mahallesi, Yeşilköy Halkalı Caddesi, Bakırköy",
      city: "Bakırköy",
      province: "İstanbul",
      phone: "+90 212 444 97 44",
      lat: 40.9828,
      lng: 28.7872,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "entertainment",
      name: "Viaport Outlet",
      address: "Atatürk Mahallesi, Turgut Özal Bulvarı, Pendik",
      city: "Pendik",
      province: "İstanbul",
      phone: "+90 216 564 00 00",
      lat: 40.8756,
      lng: 29.2378,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // Antalya - Eğlence
    {
      category: "entertainment",
      name: "Antalya Aquarium",
      address: "Arapsuyu Mahallesi, Dumlupınar Bulvarı, Konyaaltı",
      city: "Konyaaltı",
      province: "Antalya",
      phone: "+90 242 245 65 65",
      lat: 36.8817,
      lng: 30.6711,
      isEmergency: false,
      source: "Google Maps",
    },
    {
      category: "entertainment",
      name: "The Land of Legends Theme Park",
      address: "Kadriye Mahallesi, Atatürk Caddesi, Serik",
      city: "Serik",
      province: "Antalya",
      phone: "+90 242 715 00 00",
      lat: 36.9314,
      lng: 31.0831,
      isEmergency: false,
      source: "Google Maps",
    },
    
    // Ankara - Sağlık (Hastaneler)
    {
      category: "health",
      name: "Ankara Şehir Hastanesi",
      address: "Üniversiteler Mahallesi, Bilkent, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 552 60 00",
      lat: 39.8778,
      lng: 32.7456,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    {
      category: "health",
      name: "Hacettepe Üniversitesi Hastanesi",
      address: "Sıhhiye, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 305 15 53",
      lat: 39.9372,
      lng: 32.8625,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    {
      category: "health",
      name: "Yenimahalle Devlet Hastanesi",
      address: "Macunköy Mahallesi, Natoyolu Bulvarı, Yenimahalle",
      city: "Yenimahalle",
      province: "Ankara",
      phone: "+90 312 397 60 00",
      lat: 39.9900,
      lng: 32.7589,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    
    // İstanbul - Sağlık
    {
      category: "health",
      name: "İstanbul Şehir Hastanesi",
      address: "Başakşehir",
      city: "Başakşehir",
      province: "İstanbul",
      phone: "+90 212 400 00 00",
      lat: 41.1019,
      lng: 28.8381,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    {
      category: "health",
      name: "Kartal Dr. Lütfi Kırdar Şehir Hastanesi",
      address: "Cevizli Mahallesi, E-5 Karayolu, Kartal",
      city: "Kartal",
      province: "İstanbul",
      phone: "+90 216 441 37 00",
      lat: 40.9189,
      lng: 29.1856,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    {
      category: "health",
      name: "Ümraniye Eğitim ve Araştırma Hastanesi",
      address: "Elmalıkent Mahallesi, Adem Yavuz Caddesi, Ümraniye",
      city: "Ümraniye",
      province: "İstanbul",
      phone: "+90 216 632 18 18",
      lat: 41.0119,
      lng: 29.1144,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    
    // Antalya - Sağlık
    {
      category: "health",
      name: "Antalya Şehir Hastanesi",
      address: "Varlık Mahallesi, Kazım Karabekir Caddesi, Muratpaşa",
      city: "Muratpaşa",
      province: "Antalya",
      phone: "+90 242 444 30 07",
      lat: 36.9225,
      lng: 30.7803,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    {
      category: "health",
      name: "Antalya Eğitim ve Araştırma Hastanesi",
      address: "Kazım Karabekir Caddesi, Muratpaşa",
      city: "Muratpaşa",
      province: "Antalya",
      phone: "+90 242 249 44 00",
      lat: 36.9017,
      lng: 30.7186,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    {
      category: "health",
      name: "Kepez Devlet Hastanesi",
      address: "Varsak Mahallesi, Otogar Kavşağı, Kepez",
      city: "Kepez",
      province: "Antalya",
      phone: "+90 242 340 25 00",
      lat: 36.9467,
      lng: 30.7422,
      isEmergency: true,
      notes: "Acil Servis 7/24",
      source: "T.C. Sağlık Bakanlığı",
    },
    
    // Sağlık ocakları (non-emergency)
    {
      category: "health",
      name: "Çankaya Sağlık Ocağı",
      address: "Kavaklıdere Mahallesi, Atatürk Bulvarı, Çankaya",
      city: "Çankaya",
      province: "Ankara",
      phone: "+90 312 467 20 00",
      lat: 39.9089,
      lng: 32.8589,
      isEmergency: false,
      source: "T.C. Sağlık Bakanlığı",
    },
    {
      category: "health",
      name: "Kartal Aile Sağlığı Merkezi",
      address: "Orhantepe Mahallesi, Ankara Caddesi, Kartal",
      city: "Kartal",
      province: "İstanbul",
      phone: "+90 216 389 70 70",
      lat: 40.9089,
      lng: 29.1833,
      isEmergency: false,
      source: "T.C. Sağlık Bakanlığı",
    },
    {
      category: "health",
      name: "Muratpaşa Toplum Sağlığı Merkezi",
      address: "Şirinyalı Mahallesi, Lara Caddesi, Muratpaşa",
      city: "Muratpaşa",
      province: "Antalya",
      phone: "+90 242 238 30 00",
      lat: 36.8767,
      lng: 30.7178,
      isEmergency: false,
      source: "T.C. Sağlık Bakanlığı",
    },
  ];

  for (const p of pois) {
    await prisma.pOI.create({ data: p });
  }
  console.log(`  ✓ ${pois.length} POI (lokanta, otel, eğlence, sağlık) eklendi`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
